FROM php:7.4-fpm-alpine

RUN apk --no-cache update && apk upgrade

RUN docker-php-ext-install pdo_mysql mysqli  

#Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=. --filename=composer

RUN mv composer /usr/local/bin/

EXPOSE 80 9000
